@NetworkAPI_HostAddress = http://localhost:5112

POST  {{NetworkAPI_HostAddress}}/api/new-connection
Accept: application/json
Content-Type: application/json

{
  "targetTitle": "engineer",
  "targetCompany": "github",
  "intro": "devops engineer"
}